# Generated by Django 3.1 on 2020-08-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('swiftventure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_symbol',
            name='color',
            field=models.CharField(default='.', max_length=10),
        ),
        migrations.AlterField(
            model_name='m_symbol',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='m_symbol',
            name='symbol',
            field=models.CharField(default='.', max_length=3),
        ),
    ]
